version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./server:/app
    container_name: server
    ports:
      - 5000:5000
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume:
    driver: local
